### ISSUE TITLE
Database agnosticism (REGEXP)

### ISSUE THREAD

**Issue by rennerocha** [serpent213/mediawiki-extensions-yasec#1]
After installing the extension when I try to create a page with <EventCalendar> tag (as the example) I get this error:

"A database query error has occurred. This may indicate a bug in the software.

Notice: Uncommitted DB writes (transaction from DatabaseBase::query (DatabaseBase::query)). in /home/hscps/hsc.tia.mat.br/w/includes/db/Database.php on line 3944"

My config:
MediaWiki 1.22.0
PHP     5.3.27 (cgi-fcgi)
SQLite 3.7.7.1

**Comment by rennerocha** [comment]
After turning on the debug log (http://www.mediawiki.org/wiki/How_to_debug#Logging), I can see this error in the log:

Unstubbing $wgParser on call of $wgParser::parse from WikitextContent::getParserOutput
Parser: using preprocessor: Preprocessor_DOM
SQL ERROR: no such function: REGEXP

It seems a problem with the configuration of my SQLite and I still don't know how to fix it.

**Comment by rennerocha** [comment]
SQLite doesn't have a REGEXP function defined (http://www.sqlite.org/lang_expr.html#regexp), so the problem is in that line https://github.com/improper/mediawiki-extensions-yasec/blob/master/EventCalendar.php#L136

I will verify how to handle this issue tomorrow so I can send a correction and test the extension with SQLite databases.

**Comment by serpent213** [comment]
True, currently only MySQL is supported. I should at least add a note.

SQLite seems to require http://stackoverflow.com/questions/4663368/custom-regexp-function-to-be-used-in-a-sqlite-select-statement. PgSQL uses `x ~ y`, instead of `x REGEXP y`. Patches welcome.

The MediaWiki abstraction layer does not help here in any way.

**Comment by rennerocha** [comment]
I am working fixing the problem with SQLite.

If I have enough time I will try to fix with PostgreSQL, but it is not a promise :-)

**Comment by serpent213** [comment]
Sounds great.  :)
